/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice/index'
import { Route as BackofficeClientsRouteImport } from './routes/backoffice/clients'
import { Route as BackofficeClientsIndexRouteImport } from './routes/backoffice/clients/index'
import { Route as BackofficeClientsClientIdRouteImport } from './routes/backoffice/clients/$clientId'
import { Route as BackofficeClientsClientIdPersonalInfoRouteImport } from './routes/backoffice/clients/$clientId/personal-info'
import { Route as BackofficeClientsClientIdMedicalInfoRouteImport } from './routes/backoffice/clients/$clientId/medical-info'
import { Route as BackofficeClientsClientIdBenefitsRouteImport } from './routes/backoffice/clients/$clientId/benefits'

const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeClientsRoute = BackofficeClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => BackofficeRoute,
} as any)
const BackofficeClientsIndexRoute = BackofficeClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeClientsRoute,
} as any)
const BackofficeClientsClientIdRoute =
  BackofficeClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => BackofficeClientsRoute,
  } as any)
const BackofficeClientsClientIdPersonalInfoRoute =
  BackofficeClientsClientIdPersonalInfoRouteImport.update({
    id: '/personal-info',
    path: '/personal-info',
    getParentRoute: () => BackofficeClientsClientIdRoute,
  } as any)
const BackofficeClientsClientIdMedicalInfoRoute =
  BackofficeClientsClientIdMedicalInfoRouteImport.update({
    id: '/medical-info',
    path: '/medical-info',
    getParentRoute: () => BackofficeClientsClientIdRoute,
  } as any)
const BackofficeClientsClientIdBenefitsRoute =
  BackofficeClientsClientIdBenefitsRouteImport.update({
    id: '/benefits',
    path: '/benefits',
    getParentRoute: () => BackofficeClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/backoffice/clients': typeof BackofficeClientsRouteWithChildren
  '/backoffice/': typeof BackofficeIndexRoute
  '/backoffice/clients/$clientId': typeof BackofficeClientsClientIdRouteWithChildren
  '/backoffice/clients/': typeof BackofficeClientsIndexRoute
  '/backoffice/clients/$clientId/benefits': typeof BackofficeClientsClientIdBenefitsRoute
  '/backoffice/clients/$clientId/medical-info': typeof BackofficeClientsClientIdMedicalInfoRoute
  '/backoffice/clients/$clientId/personal-info': typeof BackofficeClientsClientIdPersonalInfoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeIndexRoute
  '/backoffice/clients/$clientId': typeof BackofficeClientsClientIdRouteWithChildren
  '/backoffice/clients': typeof BackofficeClientsIndexRoute
  '/backoffice/clients/$clientId/benefits': typeof BackofficeClientsClientIdBenefitsRoute
  '/backoffice/clients/$clientId/medical-info': typeof BackofficeClientsClientIdMedicalInfoRoute
  '/backoffice/clients/$clientId/personal-info': typeof BackofficeClientsClientIdPersonalInfoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteWithChildren
  '/backoffice/clients': typeof BackofficeClientsRouteWithChildren
  '/backoffice/': typeof BackofficeIndexRoute
  '/backoffice/clients/$clientId': typeof BackofficeClientsClientIdRouteWithChildren
  '/backoffice/clients/': typeof BackofficeClientsIndexRoute
  '/backoffice/clients/$clientId/benefits': typeof BackofficeClientsClientIdBenefitsRoute
  '/backoffice/clients/$clientId/medical-info': typeof BackofficeClientsClientIdMedicalInfoRoute
  '/backoffice/clients/$clientId/personal-info': typeof BackofficeClientsClientIdPersonalInfoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/backoffice/clients'
    | '/backoffice/'
    | '/backoffice/clients/$clientId'
    | '/backoffice/clients/'
    | '/backoffice/clients/$clientId/benefits'
    | '/backoffice/clients/$clientId/medical-info'
    | '/backoffice/clients/$clientId/personal-info'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backoffice'
    | '/backoffice/clients/$clientId'
    | '/backoffice/clients'
    | '/backoffice/clients/$clientId/benefits'
    | '/backoffice/clients/$clientId/medical-info'
    | '/backoffice/clients/$clientId/personal-info'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/backoffice/clients'
    | '/backoffice/'
    | '/backoffice/clients/$clientId'
    | '/backoffice/clients/'
    | '/backoffice/clients/$clientId/benefits'
    | '/backoffice/clients/$clientId/medical-info'
    | '/backoffice/clients/$clientId/personal-info'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/clients': {
      id: '/backoffice/clients'
      path: '/clients'
      fullPath: '/backoffice/clients'
      preLoaderRoute: typeof BackofficeClientsRouteImport
      parentRoute: typeof BackofficeRoute
    }
    '/backoffice/clients/': {
      id: '/backoffice/clients/'
      path: '/'
      fullPath: '/backoffice/clients/'
      preLoaderRoute: typeof BackofficeClientsIndexRouteImport
      parentRoute: typeof BackofficeClientsRoute
    }
    '/backoffice/clients/$clientId': {
      id: '/backoffice/clients/$clientId'
      path: '/$clientId'
      fullPath: '/backoffice/clients/$clientId'
      preLoaderRoute: typeof BackofficeClientsClientIdRouteImport
      parentRoute: typeof BackofficeClientsRoute
    }
    '/backoffice/clients/$clientId/personal-info': {
      id: '/backoffice/clients/$clientId/personal-info'
      path: '/personal-info'
      fullPath: '/backoffice/clients/$clientId/personal-info'
      preLoaderRoute: typeof BackofficeClientsClientIdPersonalInfoRouteImport
      parentRoute: typeof BackofficeClientsClientIdRoute
    }
    '/backoffice/clients/$clientId/medical-info': {
      id: '/backoffice/clients/$clientId/medical-info'
      path: '/medical-info'
      fullPath: '/backoffice/clients/$clientId/medical-info'
      preLoaderRoute: typeof BackofficeClientsClientIdMedicalInfoRouteImport
      parentRoute: typeof BackofficeClientsClientIdRoute
    }
    '/backoffice/clients/$clientId/benefits': {
      id: '/backoffice/clients/$clientId/benefits'
      path: '/benefits'
      fullPath: '/backoffice/clients/$clientId/benefits'
      preLoaderRoute: typeof BackofficeClientsClientIdBenefitsRouteImport
      parentRoute: typeof BackofficeClientsClientIdRoute
    }
  }
}

interface BackofficeClientsClientIdRouteChildren {
  BackofficeClientsClientIdBenefitsRoute: typeof BackofficeClientsClientIdBenefitsRoute
  BackofficeClientsClientIdMedicalInfoRoute: typeof BackofficeClientsClientIdMedicalInfoRoute
  BackofficeClientsClientIdPersonalInfoRoute: typeof BackofficeClientsClientIdPersonalInfoRoute
}

const BackofficeClientsClientIdRouteChildren: BackofficeClientsClientIdRouteChildren =
  {
    BackofficeClientsClientIdBenefitsRoute:
      BackofficeClientsClientIdBenefitsRoute,
    BackofficeClientsClientIdMedicalInfoRoute:
      BackofficeClientsClientIdMedicalInfoRoute,
    BackofficeClientsClientIdPersonalInfoRoute:
      BackofficeClientsClientIdPersonalInfoRoute,
  }

const BackofficeClientsClientIdRouteWithChildren =
  BackofficeClientsClientIdRoute._addFileChildren(
    BackofficeClientsClientIdRouteChildren,
  )

interface BackofficeClientsRouteChildren {
  BackofficeClientsClientIdRoute: typeof BackofficeClientsClientIdRouteWithChildren
  BackofficeClientsIndexRoute: typeof BackofficeClientsIndexRoute
}

const BackofficeClientsRouteChildren: BackofficeClientsRouteChildren = {
  BackofficeClientsClientIdRoute: BackofficeClientsClientIdRouteWithChildren,
  BackofficeClientsIndexRoute: BackofficeClientsIndexRoute,
}

const BackofficeClientsRouteWithChildren =
  BackofficeClientsRoute._addFileChildren(BackofficeClientsRouteChildren)

interface BackofficeRouteChildren {
  BackofficeClientsRoute: typeof BackofficeClientsRouteWithChildren
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteChildren: BackofficeRouteChildren = {
  BackofficeClientsRoute: BackofficeClientsRouteWithChildren,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteWithChildren = BackofficeRoute._addFileChildren(
  BackofficeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
